# Generated by Django 4.2.16 on 2024-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
